export const ACTIONS = {
    LISTEN: 'LISTEN',
    RESPONSE: 'RESPONSE',
    COPY: 'COPY',
    OPEN_EXTENSION: 'OPEN_EXTENSION',
    GET_AUTH_TOKEN: 'GET_AUTH_TOKEN',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    LOGOUT: 'LOGOUT',
    NEXTAUTH_TOKEN: 'NEXTAUTH_TOKEN'
}

export const PROMPTS = {
    CORRECT: 1,
    CUSTOM: 3,
}
